repo_url: https://github.com/2418071565/2418071565.github.io.git
site_name: Made By Cyb

copyright: "CopyRight &copy CYB"
edit_uri: edit/master/docs

nav:
    - About:
          - CYB👨‍💻: index.md
          - HOBBY😋: hobbies.md
          - TODO 🧾: TODO.md
    - DSA:
          - Intro: DS_Algo.md
          - Algorithms:
                - Dynamic Programming (Incomplete):
                      - Knapsack Problem: Algorithm/DP/Knapsack/Knapsack.md
                - Binary Lifting: Algorithm/BinaryLifting/BinaryLifting.md
                - Sorting (Incomplete):
                      - Intro: Algorithm/Sort/Sort.md
                      - Bubble Sort: Algorithm/Sort/BubbleSort/Bubble.md
          - Strings:
                - Trie: String/Trie/Trie.md
                - String Hashing: String/StringHash/StringHash.md
                - KMP: String/KMP/KMP.md
                - Manacher: String/Manacher/Manacher.md
          - Data Structures:
                - Heap:
                      - Binary Heap: DS/Heap/BinHp.md
                - Hash Table: DS/HTable/HTable.md
                - Union-Find: DS/UnionFind/UF.md
                - Block: DS/Block/Block.md
                - Binary Indexed Tree:
                      - BIT: DS/BIT/BIT.md
                      - 2D BIT: DS/BIT/2_BIT.md
                - Balanced Search Trees:
                      - Splay: DS/Splay/Splay.md
                      - B Tree: DS/BTree/BTree.md
                      - AVL (To be modified): DS/AVLTree/AVL.md
                - Segment Tree:
                      - Basic Segment Tree (To be modified): DS/SegTr/SegTr.md
                      - JiRuYi Segment Tree: DS/SegTr/JRYSegTr.md
                - Skip List: DS/SkipList/skiplist.md
          - Graph Theory:
                - Graph Storage: Graph/StorageOfGraphs/Storage.md
                - Topological Sort: Graph/TopoSort/Topo.md
                - Trees (Incomplete):
                      - Tree Basics: Graph/Tree/Basic/Basic.md
                      - Minimum Spanning Tree: Graph/Tree/MST/MST.md
                      - Heavy-Light Decomposition: Graph/Tree/hld/hld.md
                - Strongly Connected Components:
                      - SCC: Graph/scc/scc.md
          - Mathematics:
                - Computational Geometry:
                      - 2D Computational Geometry Basics: Math/Geometry/2DGeometry/2D.md
                      - Convex Hull: Math/Geometry/ConvexHull/CH.md
                - Number Theory:
                      - Number Theory Basics: Math/NumberTheory/Fd.md
                      - Fast Exponentiation: Math/NumberTheory/Qpow/qpow.md
                      - Multiplicative Inverse: Math/NumberTheory/Inv/Inv.md
                      - Sieve Method: Math/NumberTheory/sieve/sieve.md
                - Numerical Methods:
                      - Newton's Method: Math/Numerical/NtsMethod/Nt.md
                      - Fast Inverse Square Root: Math/Numerical/QSqrt/QSqrt.md
          - Problem Summaries:
                - Integer Partition: UsualQ/IntPartition/IntPartition.md
                - Maximum Subarray Sum: UsualQ/MaxSumOfSub/MaxSumOfSub.md
    - OS:
          - Intro: os/index.md
          - Tools:
                - Commands (Incomplete): os/Tools/Cmd/Cmd.md
                - System Calls: os/Tools/Syscall/Syscall.md
                - GNU Toolchain:
                      - gcc: os/Tools/GNU/gcc/gcc.md
                      - gdb: os/Tools/GNU/gdb/gdb.md
                      - make: os/Tools/GNU/make/make.md
                      - flex: os/Tools/GNU/flex_yacc/flex.md
          - Basic Knowledge:
                - Concepts: os/SysConcept/SysConcept.md
                - Processes:
                      - Process Concepts: os/ProCon/ProCon.md
                      - Process States: os/ProStatus/ProStatus.md
                      - Process Control: os/ProCtrl/ProCtrl.md
                      - Inter-process Communication: os/IPC/IPC.md
                      - Daemon Processes: os/DaePro/DaePro.md
                - Signals: os/Signal/signal.md
                - Threads:
                      - Thread Basics: os/Thread/Thread.md
                      - Thread Synchronization: os/Thread/Sync.md
                      - Thread Pool: os/Thread/Tpool.md
                - File Systems:
                      - Basic IO: os/FileSys/FileIO/FileIO.md
                      - ext2 File System: os/FileSys/FileSys/FileSys.md
                      - Virtual File System: os/FileSys/VFS/VFS.md
                - I/O:
                      - I/O Models: os/IO/IOmodel/model.md
                      - Multiplexing: os/IO/Multiplexing/Multiplexing.md
          - Others:
                - Root Directory: os/others/root/root.md
                - Environment Variables: os/others/envir/envir.md
                - Dynamic & Static Libraries: os/others/Lib/Lib.md
                - SheBang: os/others/sheBang/sheBang.md
    - Network:
          - Intro: Network/index.md
          - Terminology: Network/pro_term.md
          - Application Layer:
                - Overview: Network/Application/index.md
                - HTTP: Network/Application/http.md
                - DHCP: Network/Application/dhcp.md
          - Transport Layer:
                - Overview: Network/Transport/index.md
                - UDP: Network/Transport/udp.md
                - TCP: Network/Transport/tcp.md
          - Network Layer:
                - Overview: Network/network/index.md
                - IPv4: Network/network/ip.md
                - ICMP: Network/network/icmp.md
                - Firewall:
                        - Netfilter & iptables: Network/network/firewall/iptables.md
          - Link Layer:
                - Overview: Network/link/index.md
                - Ethernet: Network/link/Ethernet.md
          - Programming:
                - Basics: Network/basic/basic.md
                - Custom Protocol: Network/socket/Custom.md
                - Socket: Network/socket/socket.md
    - Programming Languages:
          - C++:
                - Intro: C++/intro.md
                - Basics: C++/c++初阶杂项.md
                - Template Basics: C++/模板.md
                - Inheritance & Polymorphism:
                      - Inheritance: C++/继承多态/继承.md
                      - Polymorphism: C++/继承多态/多态.md
                - Memory Management: C++/内存管理/new&delete.md
                - Exception Handling: C++/异常处理/异常.md
                - Type Casting: C++/typeCast.md
                - I/O Streams: C++/IO流/IO.md
                - C++11:
                      - List Initialization: C++/c++11/列表初始化.md
                      - New Features for Classes: C++/c++11/类的新功能.md
                      - Type Declarations: C++/c++11/类型声明.md
                      - Raw Strings: C++/c++11/原始字符串.md
                      - Rvalue References & Move Semantics: C++/c++11/右值引用和移动语义.md
                      - Smart Pointers: C++/c++11/智能指针.md
                      - STL Changes (Incomplete): C++/c++11/STL.md
                      - Templates: C++/c++11/cppmate.md
                      - Multithreading: C++/c++11/多线程.md
                - C++14:
                      - Templates: C++/c++14/cppmate.md
                      - decltype(auto): C++/c++14/decltype(auto).md
                - C++17:
                      - Templates: C++/c++17/cppmate.md
                      - Filesystem: C++/c++17/filesystem.md
                      - if Statements: C++/c++17/ifstatement.md
                      - Structured Bindings: C++/c++17/StructBinding.md
                - C++20:
                      - Coroutine: C++/c++20/coroutine/coroutine.md
                      - Semaphore: C++/c++20/semaphore/semaphore.md
                      - Format: C++/c++20/format/format.md
                - C++ Memory Order: C++/MemoryOrder.md
                - cmake:
                      - Intro: C++/CMake/HelloWorld.md
                      - Macros And Commands: C++/CMake/command.md
          - Rust:
                - Intro: Rust/index.md
                - Concept:
                      - OnwnerShip: Rust/MainConcept/OnwnerShip.md
                      - Struct: Rust/MainConcept/Struct.md
    - Course:
          - Intro: course.md
          - CMU 15-445:
                - Intro: course/CMU15445/index.md
                - SQL:
                      - Basic Operations: course/CMU15445/SQL/BaseOp.md
                      - Table Operations: course/CMU15445/SQL/Op.md
                      - Data Types: course/CMU15445/SQL/DataType.md
                      - Table Constraints: course/CMU15445/SQL/table/constraints.md
                      - CRUD Operations on Tables: course/CMU15445/SQL/table/idsu.md
                      - MySQL Built-in Functions: course/CMU15445/SQL/table/buildin_fun.md
                      - Composite Queries: course/CMU15445/SQL/Query.md
                - Database Storage: course/CMU15445/storage/storage.md
                - Memory Management: course/CMU15445/BufferPool/BufferPool.md
                - Access Methods:
                      - Hash Tables: course/CMU15445/DS/HTable.md
                      - Tree Indexes: course/CMU15445/DS/Bplus.md
                      - Index Concurrency Control: course/CMU15445/DS/CC.md
                - Operator Execution:
                      - Sorting & Aggregation Algorithms: course/CMU15445/OpExe/sort.md
                      - Join Algorithms: course/CMU15445/OpExe/join.md
                      - Query Processing: course/CMU15445/OpExe/query.md
                      - Parallel Execution: course/CMU15445/OpExe/pe.md
                      - Query Planning & Optimization: course/CMU15445/OpExe/qo.md
                - Concurrency Control:
                      - Theory: course/CMU15445/CC/cct.md
                      - Two-Phase Locking: course/CMU15445/CC/tpl.md
                      - Timestamp Ordering: course/CMU15445/CC/TOCC.md
                      - Multi-Version Concurrency Control: course/CMU15445/CC/MVCC.md
                - Recovery And Logging:
                      - Logging Schemes: course/CMU15445/recovery/log.md
                      - Database Crash Recovery: course/CMU15445/recovery/recovery.md
                - Distributed Databases:
                      - Intro: course/CMU15445/distributed/distributed.md
                      - Distributed OLTP: course/CMU15445/distributed/OLTP.md
                      - Distributed OLAP: course/CMU15445/distributed/OLAP.md
          - MIT 6.824:
                - Intro: course/MIT6.824/index.md
                - MapReduce: course/MIT6.824/MapReduce.md
                - GFS: course/MIT6.824/gfs.md
                - Raft: course/MIT6.824/raft.md
                - Testing Distributed Systems for Linearizability: course/MIT6.824/tdsl.md
                - ZooKeeper: course/MIT6.824/zk.md
    - Paper:
          - Intro: paper/index.md
          - WiscKey: paper/WiscKey/WiscKey.md
          - ART: paper/ART/ART.md
    - Cloud:
          - Intro: cloud/index.md
          - Kubernetes:
                - Container: cloud/k8s/container.md
                - K8s Basic: cloud/k8s/k8s.md
          - ETCD:
                - Intro: cloud/etcd/etcd.md
                # - etcd-raft: cloud/etcd/etcd-raft.md
    - AI:
          - bacis: llm/basic/basic.md
          - LLM:
               - NPL: llm/npl/npl.md
    - Others:
          - Git:
                - Intro: Others/Git/index.md
          - JSON:
                - Intro: Others/JSON/index.md
          - xmake:
                - Intro: Others/xmake/index.md
                - xmake.lua Syntax: Others/xmake/config.md
          - Smart Pointer Discussion: Others/SPoiner.md
          - RocksDB:
                - Intro: Others/rocksdb/intr.md
                - MemTable: Others/rocksdb/memtable.md

theme:
    name: material
    palette:
        primary: white
    language: zh
    custom_dir: overrides/
    favicon: Web_icon.svg
    features:
        - content.code.select
        - content.code.copy
        - navigation.instant
        - navigation.tabs
        - navigation.path
        - navigation.instant.progress
        - navigation.footer
        - content.tabs.link
        - search.highlight
    icon:
        admonition:
            code: material/note-alert
        logo: Web_icon
        repo: repo_icon

markdown_extensions:
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.highlight
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.emoji:
          emoji_index: !!python/name:material.extensions.emoji.twemoji
          emoji_generator: !!python/name:material.extensions.emoji.to_svg
          options:
              custom_icons:
                  - overrides/.icons

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/2418071565/2418071565.github.io.git
        - icon: fontawesome/solid/paper-plane
          link: mailto:idlecyb@163.com
